[package]
name = "yew-notifications"
description = "Notifications components library for Yew"
version = "0.1.0"
edition = "2021"
authors = ["Pavlo Myroniuk <pspos.developqkation@gmail.com>"]
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/TheBestTvarynka/yew-notifications"

[dependencies]
