name: Deploy doc and examples
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
on:
  push:
    branches:
    - 'main'
jobs:
  check:
    name: Check code with formatter & linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Fmt'
      run: 'cargo +nightly fmt --all -- --check'

    - name: 'Clippy'
      run: 'cargo clippy --all-features -- -D warnings'

  deploy-documentation:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs: check

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

    - name: 'Build documentation'
      run: 'mkdir doc && cargo doc --release --target-dir doc --all-features -p yew-notifications --no-deps'

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0

    - name: 'Deploy documentation'
      run: 'gsutil -h "Cache-Control:no-store" -m cp -r doc/doc/* gs://${GCP_BUCKET}'

  deploy-basic-example:
    name: Deploy basic example
    runs-on: ubuntu-latest
    needs: check

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Trunk Check'
      uses: jetli/trunk-action@v0.1.0

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

    - name: 'Add WASM target'
      run: 'rustup target add wasm32-unknown-unknown'

    - name: 'Build'
      run: 'cd examples/basic && trunk build --release'

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0

    - name: 'Deploy documentation'
      run: 'ls -l && pwd && gsutil -h "Cache-Control:no-store" -m cp -r dist/* gs://${GCP_BUCKET}/examples/basic'
